{{ if not (eq .Values.secrets.kibana.username "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kibana-sidecar.fullname" . }}
  labels:
    app: {{ template "kibana-sidecar.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  username:  {{ .Values.secrets.kibana.username | b64enc | quote }}
  password: {{ .Values.secrets.kibana.password | b64enc | quote }}
{{- end }}