name: Docker Build and Push

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: |
        imageTag=$(git show --quiet --pretty=format:%cd-%h --date=format-local:%Y%m%d.%H%M%S)
        docker build -t inmoment/kibana-sidecar:$imageTag .
        docker tag inmoment/kibana-sidecar:$imageTag inmoment/kibana-sidecar:latest
